### PR TITLE
Fix the issue with imports when installed from pip

### PR DESCRIPTION
**Pull request by t0m**
Fixes issue #8

### CODE REVIEW

**Comment by jcsaaddupuy** [comment]
Hi @jeffreystarr , this PR seems to also adds python 3 compatibility (at least for the import error).
any chance for this PR to be merge and released ?

**Comment by erccarls** [comment]
@t0m Can this be merged?  I would like to use this in production and have it installed from pip.  Great library!

**Comment by zafarali** [comment]
Agreed, nice library. Using @t0m's fork.

**Comment by denfromufa** [comment]
@t0m @zafarali @wdm0006 @erccarls @jcsaaddupuy this looks like the most recent fork, can we converge on something:

https://github.com/trifacta/dateinfer

**Comment by wdm0006** [comment]
I've been releasing my separately on pypi under pydateinfer. Happy to take any PRs from other forks and continue to release them that way, or if ya'll want to converge on a different one, I'm happy to PR with my changes there.

**Comment by denfromufa** [comment]
i forgot to copy @Dharamsitejas, who contributed to trifacta branch. @wdm0006 thanks for keeping it up on PYPI.

**Comment by denfromufa** [comment]
@wdm0006 let's converge on your branch, no one else is responding.

**Comment by wdm0006** [comment]
Sounds good to me

**Pull request closed without merging**
