### PR TITLE
Fix of relative imports

### PR DESCRIPTION
**Pull request by leferrad**
Fix proposed to solve #8. See my comment on that issue

### CODE REVIEW

**Comment by leferrad** [comment]
Can anybody check this PR? Maybe @jeffreystarr or @toofishes. I would like to have this integrated in order to use this library in production, with Python3 compatibility. Thanks!!

**Review by gladykov — APPROVED** [review]

**Comment by ltskinner** [comment]
Is there a timeline on when this will be merged and redistributed to PyPI?

**Comment by robert-yxin05** [comment]
Is this repo still being maintained by the contributors? Really want this PR to be merged.

**Comment by leferrad** [comment]
@robert-yxin05 it seems this repo stopped to be maintained many years ago... so if you really need something stable, you can use the fork I've created (also years ago). Feel free to create issues in case you need something else to at least have a working version, and I will try to attend them.
Repo: https://github.com/leferrad/dateinfer

**Comment by Shoeboxam** [comment]
@leferrad: Thanks for forking it! The following import on your package still fails though:
```sh
python -m pip install dateinfer
```

```python
import dateinfer
```

> ModuleNotFoundError: No module named 'infer'

**Comment by leferrad** [comment]
@Shoeboxam as mentioned in https://github.com/jeffreystarr/dateinfer/issues/8#issuecomment-846475061, could you try again with the solution proposed in https://github.com/leferrad/dateinfer/pull/1 ? You should install it with `pip install git+https://github.com/leferrad/dateinfer.git@fix/refactor_package` at the moment since it is a fork (not in the original repo, since it is not maintained so the PR would never be merged). If everything works great, I can publish it later as a new package in Pip

**Comment by Shoeboxam** [comment]
@leferrad The fork by wdm0006 is already on pip, works, and I'm using it in production. Why would we need another another fork?

**Pull request closed without merging**
